import React from 'react';
import Header from './Header'; // Import the Header component
import Footer from './Footer'; // Import the Footer component



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
 
        <Header />
          {children}
        <Footer />

      </body>
    </html>
  )
}
